// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyX9ZB7f3DYHdyY1tuxSfy8vFrtu751_8',
    appId: '1:966727350695:web:c20c753bd7fe7388a6de82',
    messagingSenderId: '966727350695',
    projectId: 'seddo-32139',
    authDomain: 'seddo-32139.firebaseapp.com',
    storageBucket: 'seddo-32139.firebasestorage.app',
    measurementId: 'G-4ZYRSL3MKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC41p4Hj9U-SPeiI5oi07bKNp8UhJdjQw',
    appId: '1:966727350695:android:85a5ff869b595b24a6de82',
    messagingSenderId: '966727350695',
    projectId: 'seddo-32139',
    storageBucket: 'seddo-32139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG5D3IS5wmxd_VyJr0OFAV68z303u-FDU',
    appId: '1:966727350695:ios:ab810cfe83fb6a31a6de82',
    messagingSenderId: '966727350695',
    projectId: 'seddo-32139',
    storageBucket: 'seddo-32139.firebasestorage.app',
    iosBundleId: 'com.wakana.seddo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG5D3IS5wmxd_VyJr0OFAV68z303u-FDU',
    appId: '1:966727350695:ios:66279eefd9296aeca6de82',
    messagingSenderId: '966727350695',
    projectId: 'seddo-32139',
    storageBucket: 'seddo-32139.firebasestorage.app',
    iosBundleId: 'com.wakana.seddo.RunnerTests',
  );
}
